{
    'name': 'niubiz: método de pago',
    'category': 'Accounting',
    'summary': 'Modulo que permite generar pagos con NIUBIZ',
    'version': '1.0',
    'price': 250,
    'currency': "USD",
    'license': 'OPL-1',
    'live_test_url': 'https://www.youtube.com/watch?v=DpYciZcaG-U',
    'author': 'WILFREDO CRISTOBAL OLANO CHAVEZ',
    'description': """Método de pago con NIUBIZ""",
    'website': "https://www.youtube.com/watch?v=DpYciZcaG-U",

    'depends': ['payment', 'website_sale','sale','web', 'base'],
    'application': True,
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'views/payment_niubiz_templates.xml',
        'data/payment_acquirer_data.xml',
        'data/payment_method_data.xml',
        'views/payment_views.xml',
        'views/view_custom_results_niubiz.xml',
        'views/view_niubiz_list_action.xml',
        "views/report/sale_order_report.xml",
        'views/email/email_sale.xml',
        'views/view_sale_order_web.xml',
        'views/email/email_payment_confirmation.xml',
        'views/server/ir.cron.xml',
        'views/inherit_company_form.xml',
        "views/inherit_total_web.xml",
    ],
    'assets': {
        'web.assets_frontend': [
            '/niubiz_payment/static/src/js/payment_form.js',
            # '/niubiz_payment/static/src/js/niubiz_payment.js',
            # '/niubiz_payment/static/src/js/niubiz_new.js',
            '/niubiz_payment/static/src/js/niubiz.js',
            '/niubiz_payment/static/src/css/index.css',            
        ],
    },
    # 'post_init_hook': 'create_missing_journal_for_acquirers',
    'installable': True,
    'auto_install': False,
    "images": ['static/description/b3.png', 'static/description/b4.png'],
}
